In [3]:
import numpy as np
array_a = np.array([[1,4,5,7,8],[5,4,0,1,6],[3,5,8,0,9]])
array_a

array([[1, 4, 5, 7, 8],
       [5, 4, 0, 1, 6],
       [3, 5, 8, 0, 9]])

In [4]:
np.min(array_a)

0

In [5]:
np.max(array_a)

9

In [6]:
np.min(array_a, axis=1)

array([1, 0, 0])

In [7]:
np.max(array_a, axis=1)

array([8, 6, 9])

In [8]:
np.amax(array_a)

9

In [9]:
np.mean(array_a, axis=0)

array([3.        , 4.33333333, 4.33333333, 2.66666667, 7.66666667])

In [10]:
array_a.mean()

4.4

In [11]:
array_a

array([[1, 4, 5, 7, 8],
       [5, 4, 0, 1, 6],
       [3, 5, 8, 0, 9]])

In [12]:
np.minimum(array_a[0], array_a[1])

array([1, 4, 0, 1, 6])

In [13]:
np.maximum(array_a[0], array_a[1])

array([5, 4, 5, 7, 8])

In [14]:
np.maximum.reduce(array_a)

array([5, 5, 8, 7, 9])

_**Statistical Order Function in Numpy**_


In [15]:
np.ptp(array_a)

9

In [16]:
array_a

array([[1, 4, 5, 7, 8],
       [5, 4, 0, 1, 6],
       [3, 5, 8, 0, 9]])

In [17]:
np.ptp(array_a, axis=0)

array([4, 1, 8, 7, 3])

In [18]:
np.sort(array_a, axis= None)

array([0, 0, 1, 1, 3, 4, 4, 5, 5, 5, 6, 7, 8, 8, 9])

In [19]:
np.percentile(array_a, 50, interpolation='nearest')

/tmp/ipykernel_910/2766741398.py:1: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  np.percentile(array_a, 50, interpolation='nearest')


5

In [24]:
import numpy as np
np.quantile(array_a, 0.70, interpolation = 'nearest')

/tmp/ipykernel_910/2759851245.py:2: DeprecationWarning: the `interpolation=` argument to quantile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  np.quantile(array_a, 0.70, interpolation = 'nearest')


6

In [26]:
np.average(array_a)

4.4

In [27]:
np.mean(array_a)

4.4

In [32]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

array_RG = gen(pcg(seed= 365))
array_RG.random(size=(3,5))

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736]])

In [33]:
array_a

array([[1, 4, 5, 7, 8],
       [5, 4, 0, 1, 6],
       [3, 5, 8, 0, 9]])

In [35]:
np.average(array_a, weights=array_RG)

TypeError: 1D weights expected when shapes of a and weights differ.

In [36]:
np.var(array_a)

8.106666666666667

In [40]:
np.std(array_a)

2.8472208672083497

In [38]:
2.84**2

8.0656

In [42]:
np.cov(array_a)

array([[ 7.5 , -1.  ,  2.5 ],
       [-1.  ,  6.7 ,  2.25],
       [ 2.5 ,  2.25, 13.5 ]])

In [43]:
np.corrcoef(array_a)

array([[ 1.        , -0.14106912,  0.248452  ],
       [-0.14106912,  1.        ,  0.23658011],
       [ 0.248452  ,  0.23658011,  1.        ]])

In [45]:
np.histogram(array_a, bins = 4)

(array([4, 3, 4, 4]), array([0.  , 2.25, 4.5 , 6.75, 9.  ]))

In [0]:
import matplotlib.pyplot as mp
mp.hist()