In [3]:
import numpy as np

array_a = np.array([1, 3, 6])
array_a

array([1, 3, 6])

In [4]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [5]:
array_c = np.array([[1,4,8],[4,7,12]])
array_c

array([[ 1,  4,  8],
       [ 4,  7, 12]])

In [6]:
array_a[-2]

3

In [7]:
array_c[1, 2]

12

In [8]:
array_a +2

array([3, 5, 8])

In [9]:
array_a + array_b

array([[2, 4, 7],
       [3, 5, 8]])

In [10]:
np.add(array_a, array_b )

array([[2, 4, 7],
       [3, 5, 8]])

In [11]:
array_c

array([[ 1,  4,  8],
       [ 4,  7, 12]])

In [12]:
array_c[:,2] =9

In [13]:
array_c

array([[1, 4, 9],
       [4, 7, 9]])

In [14]:
array_c[0,:] =2

In [15]:
array_c

array([[2, 2, 2],
       [4, 7, 9]])

In [16]:
np.mean(array_c, axis= 1, dtype=np.bool8)

array([ True,  True])

In [17]:
np.array_equal(array_a, array_c)

False

In [18]:
type(array_a)

numpy.ndarray

In [19]:
type(array_b)

numpy.ndarray

In [20]:
array_a == array_b

array([[ True, False, False],
       [False, False, False]])

In [21]:
array_1 = np.array([1, 2, 3, 4, 6])
array_2 = np.array([1, 2, 3, 4, 6])
np.array_equal(array_1, array_2)

True

In [22]:
list_1 = [1, 2, 4, 5]
list_1 + [3]

[1, 2, 4, 5, 3]

In [23]:
list_a = [[2, 3, 5], [6, 7, 8]]
list_a

[[2, 3, 5], [6, 7, 8]]

In [24]:
import numpy as np
array_A = np.array(list_a)
array_A

array([[2, 3, 5],
       [6, 7, 8]])

In [25]:
len(list_a)

2

In [26]:
array_A.shape

(2, 3)

In [27]:
list_a[1] + list_a[0]

[6, 7, 8, 2, 3, 5]

In [28]:
array_A[0] +array_A[1]

array([ 8, 10, 13])

In [29]:
array_A[1,2]

8

In [30]:
n_array = np.array([15])
n_array

array([15])

In [31]:
print(n_array)

[15]


In [32]:
n_array.shape

(1,)

In [33]:
n1_array = np.array([[15]])
n1_array

array([[15]])

In [34]:
n1_array.shape

(1, 1)

In [35]:
company_data = np.genfromtxt('Lending-company-csv.csv', 
                             delimiter=',', 
                             dtype= np.object0)
print(company_data)

[[b'Loan ID' b'String_ID' b'Product' ... b'AmountPaid60' b'AmountPaid360'
  b'LoanStatus360']
 [b'1' b'id_1' b'Product B' ... b'4241' b'13621' b'Active']
 [b'2' b'id_2' b'Product B' ... b'4171' b'15041' b'Active']
 ...
 [b'1041' b'id_1041' b'Product B' ... b'5001' b'16600'
  b'Finished Payment']
 [b'1042' b'id_1042' b'Product C' ... b'3320' b'15600'
  b'Finished Payment']
 [b'1043' b'id_1043' b'Product B' ... b'4601' b'16600'
  b'Finished Payment']]


In [36]:
company_data[0,0]+ company_data[0,1]

b'Loan IDString_ID'

In [37]:
import numpy as np
a_1 = np.array([[2,5,6],[4,5,7],[3,9,5]])
a_1

array([[2, 5, 6],
       [4, 5, 7],
       [3, 9, 5]])

In [38]:
a_1[0:2,:-1]

array([[2, 5],
       [4, 5]])

In [39]:
a_1[1,2]

7

In [40]:
a_1

array([[2, 5, 6],
       [4, 5, 7],
       [3, 9, 5]])

In [41]:
a_1[::,::]

array([[2, 5, 6],
       [4, 5, 7],
       [3, 9, 5]])

In [42]:
a_1[::2, ::2]

array([[2, 6],
       [3, 5]])

In [43]:
a_1[0:1:2,0:1:2]

array([[2]])

In [44]:
type(a_1[0:1:2,0:1:2])

numpy.ndarray

In [45]:
a_1[0:1:2,0:1:2].squeeze().shape

()

In [46]:
a_1[(a_1[:, :] %2 == 0) | (a_1[:, :]< 6)]

array([2, 5, 6, 4, 5, 3, 5])

In [48]:
import numpy as np

array_0 = np.zeros(shape=(2,3))
array_0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
array_emp = np.empty(shape=(2,3))
array_emp

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
array_one = np.ones(shape=(2,3))
array_one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
array_full = np.full(shape=(2,3), fill_value='Giri')
array_full

array([['Giri', 'Giri', 'Giri'],
       ['Giri', 'Giri', 'Giri']], dtype='<U4')

In [53]:
array_ze = np.array([[3,4,5,6,7],[4,6,7,8,9],[1,3,5,7,0]])
np.empty_like(array_ze)

array([[93990017302614,              0,              0,              0,
                     0],
       [             0,              0,              0,              0,
                     0],
       [             0,              0,              0,              0,
                   128]])

In [56]:
np.arange(start = 1, stop = 31, step = 2.5
         )

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5, 21. , 23.5, 26. ,
       28.5])

In [65]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

array_RG = gen(pcg())
array_RG.normal(size=(5,5))

array([[-0.30041228,  0.01814614,  1.17655188,  0.2606409 , -0.88186503],
       [ 1.57505905, -0.71323907, -0.62512579, -0.93738279,  0.54025567],
       [-0.78691724, -0.96800325, -1.28408127, -0.34215399, -0.37442884],
       [ 0.19640946,  1.24906117, -0.15164829, -0.89776814,  0.67190707],
       [-0.75534855,  1.22322053,  0.86048992, -0.96736847, -0.17731792]])

In [67]:
array_RG.normal(size=(5,5))

array([[-0.41967836, -0.71632755, -0.32826723, -1.06438295,  0.9035792 ],
       [-0.07628975, -0.28720131,  1.22152984,  0.21908888, -0.61155296],
       [ 0.28933083,  0.89725154, -0.50376467, -0.22591547, -2.16258156],
       [-1.9431065 , -1.12071556,  1.02306798,  0.43739163, -0.73235252],
       [ 0.94672257,  0.87782658, -0.23792642,  0.43373642, -0.2923595 ]])

In [70]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

array_RG = gen(pcg(seed=365))
array_RG.normal(size=(5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [73]:
array_RG.normal(size=(5,5))

array([[ 0.88049508, -0.24918091, -0.1624507 ,  1.18895278, -0.22199353],
       [ 0.22865664, -0.51721829, -0.29077458, -0.09899225, -0.513059  ],
       [-0.33227255, -0.89147912, -1.65797893,  0.62909218, -0.98318875],
       [-0.02153055,  1.27926297,  1.62188437, -0.56612507, -0.51265843],
       [ 0.64317322,  0.03355112, -0.78542576,  2.4075666 ,  0.28802775]])

In [79]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

array_RG = gen(pcg(seed=365))
array_RG.integers(low = 2, high = 13,size=(5,5))

array([[ 3, 10,  8, 10, 11],
       [ 8,  9,  4,  2,  9],
       [ 6,  2,  5,  9, 12],
       [ 3,  3, 11,  9,  7],
       [ 7, 11,  8,  7, 12]])

In [86]:
array_RG = gen(pcg(seed=365))
array_RG.random(size=(5,5), dtype = np.float64)

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [83]:
array_RG = gen(pcg(seed=365))
array_RG.choice([1, 2, 4, 5], size=(5,5))

array([[1, 5, 4, 5, 5],
       [4, 4, 1, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 2],
       [2, 5, 4, 2, 5]])

In [92]:
array_dist = gen(pcg(seed=365))
array_dist.poisson(lam =10, size = (5,5))

array([[11, 12, 12, 14, 13],
       [ 9, 10, 11, 11,  8],
       [11,  8, 10,  9, 14],
       [ 7,  8,  9, 15, 15],
       [13,  8,  8,  7,  9]])

In [94]:
array_dist = gen(pcg(seed=365))
array_dist.binomial(n = 100, p = 0.4, size = (5,5))

array([[42, 44, 30, 36, 45],
       [36, 41, 38, 42, 41],
       [35, 31, 35, 46, 29],
       [41, 41, 46, 34, 48],
       [45, 45, 45, 40, 43]])