In [3]:
import numpy as np
np.set_printoptions(suppress=True, linewidth=100, precision=2)
loan_data = np.genfromtxt('loan-data.csv',
                           delimiter=';',
                           autostrip=True,
                           skip_header=1)
print(loan_data)

[[48010226.           nan    35000.   ...         nan         nan     9452.96]
 [57693261.           nan    30000.   ...         nan         nan     4679.7 ]
 [59432726.           nan    15000.   ...         nan         nan     1969.83]
 ...
 [50415990.           nan    10000.   ...         nan         nan     2185.64]
 [46154151.           nan         nan ...         nan         nan     3199.4 ]
 [66055249.           nan    10000.   ...         nan         nan      301.9 ]]


In [4]:
np.isnan(loan_data).sum()

88005

In [5]:
temp_fill = np.nanmax(loan_data) + 1
temp_mean = np.nanmean(loan_data, axis=0)

/tmp/ipykernel_2379/3914187566.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(loan_data, axis=0)


In [6]:
temp_fill.round(2)

68616520.0

In [7]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [8]:
temp_stat = np.array([np.nanmin(loan_data, axis=0),
                     temp_mean,
                     np.nanmax(loan_data, axis=0)])
temp_stat

/tmp/ipykernel_2379/3375212269.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stat = np.array([np.nanmin(loan_data, axis=0),
/tmp/ipykernel_2379/3375212269.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(loan_data, axis=0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [9]:
column_strings = np.argwhere(np.isnan(temp_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [10]:
column_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13])

In [11]:
import numpy as np
np.set_printoptions(suppress=True, linewidth=100, precision=2)
loan_data_string = np.genfromtxt('loan-data.csv',
                           delimiter=';',
                           autostrip=True,
                           skip_header=1,
                           usecols=column_strings,
                           dtype=np.str)
print(loan_data_string)

/tmp/ipykernel_2379/3599792072.py:8: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.str)


[['May-15' 'Current' '36 months' ... 'Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226' 'CA']
 ['' 'Current' '36 months' ... 'Source Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261' 'NY']
 ['Sep-15' 'Current' '36 months' ... 'Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726' 'PA']
 ...
 ['Jun-15' 'Current' '36 months' ... 'Source Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990' 'CA']
 ['Apr-15' 'Current' '36 months' ... 'Source Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151' 'OH']
 ['Dec-15' 'Current' '36 months' ... ''
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249' 'IL']]


In [12]:
import numpy as np
np.set_printoptions(suppress=True, linewidth=100, precision=2)
loan_data_numeric = np.genfromtxt('loan-data.csv',
                           delimiter=';',
                           autostrip=True,
                           skip_header=1,
                           usecols=column_numeric,
                           filling_values=temp_fill)
print(loan_data_numeric)

[[48010226.      35000.      35000.         13.33     1184.86     9452.96]
 [57693261.      30000.      30000.   68616520.        938.57     4679.7 ]
 [59432726.      15000.      15000.   68616520.        494.86     1969.83]
 ...
 [50415990.      10000.      10000.   68616520.   68616520.       2185.64]
 [46154151.   68616520.      10000.         16.55      354.3      3199.4 ]
 [66055249.      10000.      10000.   68616520.        309.97      301.9 ]]

In [13]:
header_full = np.genfromtxt('loan-data.csv',
                           delimiter=';',
                           autostrip=True,
                           skip_footer=loan_data.shape[0],
                           dtype=np.str
                           )
                           
header_full                        

/tmp/ipykernel_2379/402898560.py:5: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.str


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [14]:
header_string, header_numeric = header_full[column_strings], header_full[column_numeric]

In [15]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [16]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [17]:
def checkpoint(fileName, checkpoint_Header, checkpoint_Data):
    np.savez(fileName, header = checkpoint_Header, data=checkpoint_Data)
    checkpoint_variable = np.load(fileName + '.npz')
    return(checkpoint_variable)

In [18]:
checkpoint_text = checkpoint('checkpoint-text', header_string, loan_data_string)

In [19]:
checkpoint_text.files

['header', 'data']

In [20]:
checkpoint_text['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [21]:
checkpoint_text['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

Issue Date


In [22]:
loan_data_string[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [23]:
loan_data_string[:,0] = np.chararray.strip(loan_data_string[:,0], '-15')

In [24]:
np.unique(loan_data_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [25]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [26]:
for i in range(13):
    loan_data_string[:,0] = np.where(loan_data_string[:,0] == months[i],
            i,
            loan_data_string[:,0])

In [27]:
np.unique(loan_data_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [28]:
header_string[0] = 'Issue_date'

Loan Status


In [29]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [30]:
bad_status = np.array(['', 'Charged Off', 'Late (31-120 days)', 'Default'])

In [31]:
loan_data_string[:,1] = np.where(np.isin(loan_data_string[:,1], bad_status), 0, 1)

In [32]:
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

Term


In [33]:
loan_data_string[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [34]:
loan_data_string[:,2] = np.chararray.strip(loan_data_string[:,2], ' months')
loan_data_string[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [35]:
np.unique(loan_data_string[:,2])

array(['', '36', '60'], dtype='<U69')

In [36]:
loan_data_string[:,2] = np.where(loan_data_string[:,2] == '',
                                60,
                                loan_data_string[:,2])

In [37]:
np.unique(loan_data_string[:,2])

array(['36', '60'], dtype='<U69')

Grade & Sub Grade


In [38]:
np.unique(loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [39]:
np.unique(loan_data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [40]:
for i in loan_data_string[:,3]:
    loan_data_string[:,4] = np.where((loan_data_string[:,4] == '') & (loan_data_string[:,3] == i),
                                    i + '5',
                                    loan_data_string[:,4])
    

In [41]:
np.unique(loan_data_string[:,4], return_counts= True)

(array(['5', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [42]:
loan_data_string[:,4] = np.where(loan_data_string[:,4] == '5',
                                'H1',
                                loan_data_string[:,4])

In [43]:
np.unique(loan_data_string[:,4], return_counts= True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9]))

Delete Grade


In [44]:
loan_data_string = np.delete (loan_data_string, 3, axis=1)

In [45]:
header_string = np.delete(header_string,3)

In [46]:
loan_data_string[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [47]:
np.unique(loan_data_string[:,3]).shape

(36,)

In [48]:
keys = list(np.unique(loan_data_string[:,3]))
values = list(range(1,np.unique(loan_data_string[:,3]).shape[0] +1))
sub_grade_dict = dict(zip(keys, values))

In [49]:
sub_grade_dict

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [50]:
for i in np.unique(loan_data_string[:,3]):
                   loan_data_string[:,3] = np.where(loan_data_string[:,3] == i,
                                                                       sub_grade_dict[i],
                                                                       loan_data_string[:,3])

In [51]:
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

Status & URL


In [52]:
np.unique(loan_data_string[:,4], return_counts= True)

(array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69'),
 array([ 500, 2673, 4116, 2711]))

In [53]:
loan_data_string[:,4] = np.where((loan_data_string[:,4] == '') | (loan_data_string[:,4] == 'Not Verified'),
                                0,1)

In [54]:
loan_data_string[:,5] = np.chararray.strip(loan_data_string[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [55]:
loan_data_string[:,5].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [56]:
loan_data_numeric[:,0].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [57]:
loan_data_string = np.delete(loan_data_string, 5, axis=1)

In [58]:
loan_data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [59]:
header_string = np.delete(header_string, 5)

In [60]:
header_string

array(['Issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [61]:
data, count = np.unique(loan_data_string[:,5], return_counts= True)
sort_count = np.argsort(-count)

data[sort_count], count[sort_count]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [62]:
loan_data_string[:,5] = np.where(loan_data_string[:,5] == '',
                                0,
                                loan_data_string[:,5])

In [63]:
np.unique(loan_data_string[:,5])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [64]:
states_west = np.array(['WA', 'OR', 'CA','NV','ID','MT','WY','UT','CO','AZ','NM','HI','AK'])
states_south = np.array(['TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'TN', 'KY', 'FL', 'GA', 'SC', 'NC', 'VA', 'WV', 'MD', 'DE', 'DC'])
states_midwest = np.array(['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'IN', 'MI', 'OH'])
states_east = np.array(['PA', 'NY', 'NJ', 'CT','MA', 'VT', 'NH', 'ME', 'RI'])

In [65]:
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5],states_west), 1, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5],states_south), 2, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5],states_midwest), 3, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5],states_east), 4, loan_data_string[:,5])

In [66]:
np.unique(loan_data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [67]:
loan_data_string = loan_data_string[:].astype(dtype=np.int32)

In [68]:
loan_data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], dtype=int32)

In [69]:
def checkpoint(checkpoint_header, checkpoint_data, fileName):
    np.savez(fileName, header = checkpoint_header,  data = checkpoint_data)
    check_variable = np.load(fileName+ '.npz')
    return(check_variable)

In [70]:
check_Loan_String = checkpoint(header_string, loan_data_string, 'Checkpoint-string')

In [71]:
check_Loan_String.files

['header', 'data']

In [72]:
check_Loan_String['header']

array(['Issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [73]:
check_Loan_String['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], dtype=int32)

In [74]:
np.array_equal(check_Loan_String['data'], loan_data_string)

True

In [75]:
temp_stat

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [76]:
temp_stat[:,column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [77]:
np.isnan(loan_data_numeric).sum()

0

In [78]:
np.isin(loan_data_numeric[:,0], temp_fill).sum()

0

In [79]:
for i in range(1,6):
        loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temp_fill,
                                         temp_stat[0,column_numeric[i]],
                                         loan_data_numeric[:,i])
#      print(i, end = " ")

In [80]:
 loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,        6.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,        6.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,        6.  ,       31.42,     2185.64],
       [46154151.  ,     1000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,        6.  ,      309.97,      301.9 ]])

In [81]:
loan_data_numeric.shape

(10000, 6)

In [82]:
column_numeric.shape

(6,)

In [83]:
USD_Data = np.genfromtxt('EUR-USD.csv',
               delimiter = ',',
               autostrip= True,          
#                dtype = np.str,
               skip_header=1,
               usecols=3                
             )
USD_Data                            

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [84]:
np.sort(np.unique(loan_data_string[:,0])
       )

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [85]:
exchange_rate = loan_data_string[:,0]

for i in range(1,13):
    
    exchange_rate = np.where(exchange_rate == i,
                            USD_Data[i-1],
                            exchange_rate)
exchange_rate = np.where(exchange_rate == 0,
                            np.mean(USD_Data),
                            exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [86]:
exchange_rate.shape

(10000,)

In [87]:
loan_data_numeric.shape

(10000, 6)

In [88]:
exchange_rate = np.reshape(exchange_rate, (10000, 1))

In [89]:
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))

In [90]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,       31.42,     2185.64,        1.12],
       [46154151.  ,     1000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [91]:
header_numeric = np.concatenate((header_numeric, np.array(['Exchange_Rate'])))

In [92]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'Exchange_Rate'],
      dtype='<U19')

From USD to EUR



In [93]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,       31.42,     2185.64,        1.12],
       [46154151.  ,     1000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [94]:
column_dollar = np.array([1, 2, 4, 5])

In [95]:
for i in column_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000, 1))))

In [96]:
loan_data_numeric.shape

(10000, 11)

In [97]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,       28.  ,     1947.47],
       [46154151.  ,     1000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [98]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[column_dollar]])

In [99]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [100]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [101]:
header_numeric.shape

(11,)

In [102]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'Exchange_Rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [103]:
header_numeric[column_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[column_dollar]])

In [104]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'Exchange_Rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

Interest Rate



In [105]:
loan_data_numeric[:,3] = loan_data_numeric[:,3]/100

In [106]:
loan_data_numeric[:,3]

array([0.13, 0.06, 0.06, ..., 0.06, 0.17, 0.06])

In [107]:
loan_data_string.shape

(10000, 6)

In [108]:
loan_data_numeric.shape

(10000, 11)

In [112]:
check_Loan_numeric = checkpoint(header_numeric, loan_data_numeric, 'Checkpoint-numeric')

In [113]:
check_Loan_numeric['header']

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'Exchange_Rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [114]:
final_header = np.hstack((check_Loan_numeric['header'], check_Loan_String['header']))

In [115]:
final_header

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'Exchange_Rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR',
       'Issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [116]:
final_loan_data = np.hstack((check_Loan_numeric['data'], check_Loan_String['data']))

In [117]:
final_loan_data

array([[48010226.,    35000.,    35000., ...,       13.,        1.,        1.],
       [57693261.,    30000.,    30000., ...,        5.,        1.,        4.],
       [59432726.,    15000.,    15000., ...,       10.,        1.,        4.],
       ...,
       [50415990.,    10000.,    10000., ...,        5.,        1.,        1.],
       [46154151.,     1000.,    10000., ...,       17.,        1.,        3.],
       [66055249.,    10000.,    10000., ...,        4.,        0.,        3.]])

In [118]:
loan_data = np.vstack((final_header, final_loan_data))

In [119]:
loan_data

array([['id', 'loan_amnt_USD', 'funded_amnt_USD', ..., 'sub_grade', 'verification_status',
        'addr_state'],
       ['48010226.0', '35000.0', '35000.0', ..., '13.0', '1.0', '1.0'],
       ['57693261.0', '30000.0', '30000.0', ..., '5.0', '1.0', '4.0'],
       ...,
       ['50415990.0', '10000.0', '10000.0', ..., '5.0', '1.0', '1.0'],
       ['46154151.0', '1000.0', '10000.0', ..., '17.0', '1.0', '3.0'],
       ['66055249.0', '10000.0', '10000.0', ..., '4.0', '0.0', '3.0']], dtype='<U32')

In [121]:
np.savetxt('Preprocess_Loan_Data.csv', loan_data, delimiter=',', fmt='%s')