In [3]:
import numpy as np

File_Name = 'Lending-company-Numeric.csv'

raw_data = np.loadtxt(File_Name, 
          delimiter=',')
print(raw_data)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [4]:
import numpy as np

File_Name_NAN = 'Lending-company-Numeric-NAN.csv'

raw_data_NAN = np.genfromtxt(File_Name_NAN, 
           delimiter=';',
           )
print(raw_data_NAN)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [   nan    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [5]:
temp_fill = np.nanmax(raw_data_NAN).round(2) +1
temp_fill

64002.0

In [6]:
import numpy as np

File_Name_NAN = 'Lending-company-Numeric-NAN.csv'

raw_data_NAN_1 = np.genfromtxt(File_Name_NAN, 
           delimiter=';',
           filling_values= temp_fill                   
           )
print(raw_data_NAN_1)

[[2.0000e+03 4.0000e+01 3.6500e+02 3.1210e+03 4.2410e+03 1.3621e+04]
 [2.0000e+03 4.0000e+01 3.6500e+02 3.0610e+03 4.1710e+03 1.5041e+04]
 [1.0000e+03 4.0000e+01 3.6500e+02 2.1600e+03 3.2800e+03 1.5340e+04]
 ...
 [6.4002e+04 4.0000e+01 3.6500e+02 4.2010e+03 5.0010e+03 1.6600e+04]
 [1.0000e+03 4.0000e+01 3.6500e+02 2.0800e+03 3.3200e+03 1.5600e+04]
 [2.0000e+03 4.0000e+01 3.6500e+02 4.6010e+03 4.6010e+03 1.6600e+04]]


In [7]:
np.isnan(raw_data_NAN).sum()

260

In [8]:
np.set_printoptions(suppress=True)

In [9]:
for i in range(raw_data_NAN_1.shape[1]):
    print(i, end = " ")

0 1 2 3 4 5 

In [10]:
raw_data_NAN_1.shape[0]

1043

In [11]:
Fill_1 = np.nanmean(raw_data_NAN_1, axis=0)
Fill_1[1].round(2)

2989.43

In [12]:
raw_data_NAN_1[:,0] = np.where(raw_data_NAN_1[:,0] == temp_fill,
                              Fill_1[1].round(2),
                              raw_data_NAN_1[:,0])

In [13]:
raw_data_NAN_1

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2989.43,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [14]:
for i in range(raw_data_NAN_1.shape[1]):
    raw_data_NAN_1[:,i] = np.where(raw_data_NAN_1[:,i] == temp_fill,
                              Fill_1[i].round(2),
                              raw_data_NAN_1[:,i])

In [15]:
raw_data_NAN_1

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2989.43,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [16]:
raw_data_NAN_1.shape

(1043, 6)

In [17]:
np.isnan(raw_data_NAN_1).sum()

0

In [18]:
np.reshape(raw_data_NAN_1,(6, 1043))

array([[ 2000. ,    40. ,   365. , ...,   365. ,  1581. ,  3041. ],
       [12277. ,  2000. ,    40. , ...,    50. ,   365. ,  5350. ],
       [ 6850. , 15150. ,  1000. , ...,  2000. ,    40. ,  3537.7],
       [ 3101. ,  4351. , 16600. , ..., 16600. ,  2000. ,    40. ],
       [  365. ,  3441. ,  4661. , ...,  8450. , 22250. ,  2000. ],
       [   40. ,   365. ,  3701. , ...,  4601. ,  4601. , 16600. ]])

In [19]:
np.reshape(raw_data_NAN_1,(1,1,2, 3, 1043))

array([[[[[ 2000. ,    40. ,   365. , ...,   365. ,  1581. ,  3041. ],
          [12277. ,  2000. ,    40. , ...,    50. ,   365. ,  5350. ],
          [ 6850. , 15150. ,  1000. , ...,  2000. ,    40. ,  3537.7]],

         [[ 3101. ,  4351. , 16600. , ..., 16600. ,  2000. ,    40. ],
          [  365. ,  3441. ,  4661. , ...,  8450. , 22250. ,  2000. ],
          [   40. ,   365. ,  3701. , ...,  4601. ,  4601. , 16600. ]]]]])

In [20]:
raw_data_NAN_1

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2989.43,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [21]:
np.delete(raw_data_NAN_1, [0,2,4], axis=1)

array([[   40.,  3121., 13621.],
       [   40.,  3061., 15041.],
       [   40.,  2160., 15340.],
       ...,
       [   40.,  4201., 16600.],
       [   40.,  2080., 15600.],
       [   40.,  4601., 16600.]])

In [22]:
raw_data_NAN_1[[0,3,7
              ],:]

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [23]:
#Sort_raw_data = raw_data_NAN_1.sort()
np.sort(raw_data_NAN_1, axis=None)

array([-2870., -2870., -2550., ..., 54625., 54625., 64001.])

In [24]:
raw_data_NAN_1.shape

(1043, 6)

In [25]:
np.sort(raw_data_NAN_1, axis = 0)

array([[ 1000.  ,    35.  ,   365.  , -2870.  , -2870.  ,  -350.  ],
       [ 1000.  ,    35.  ,   365.  , -2550.  , -2100.  ,  1100.  ],
       [ 1000.  ,    35.  ,   365.  , -2450.  , -1750.  ,  1160.  ],
       ...,
       [ 9000.  ,  2989.43,  3537.7 , 16001.  , 18250.  , 54625.  ],
       [ 9000.  ,  2989.43,  3537.7 , 16751.  , 18751.  , 54625.  ],
       [ 9000.  ,  2989.43,  3537.7 , 17650.  , 20001.  , 64001.  ]])

In [26]:
raw_data_NAN_1

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2989.43,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [27]:
import numpy as np

File_Name_NAN = 'Lending-company-Numeric-NAN.csv'

raw_data_NAN_1 = np.genfromtxt(File_Name_NAN, 
           delimiter=';',
           filling_values= temp_fill                   
           )
print(raw_data_NAN_1)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [64002.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [28]:
for i in range(raw_data_NAN_1.shape[1]):
    raw_data_NAN_1[:,i] = np.where(raw_data_NAN_1[:,i] == temp_fill,
                              Fill_1[i].round(2),
                              raw_data_NAN_1[:,i])

In [29]:
np.sort(raw_data_NAN_1)

array([[   40.  ,   365.  ,  2000.  ,  3121.  ,  4241.  , 13621.  ],
       [   40.  ,   365.  ,  2000.  ,  3061.  ,  4171.  , 15041.  ],
       [   40.  ,   365.  ,  1000.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [   40.  ,   365.  ,  4201.  ,  4263.25,  5001.  , 16600.  ],
       [   40.  ,   365.  ,  1000.  ,  2080.  ,  3320.  , 15600.  ],
       [   40.  ,   365.  ,  2000.  ,  4601.  ,  4601.  , 16600.  ]])

In [30]:
raw_data_NAN_1

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 4263.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [31]:
np.argsort(raw_data_NAN_1)

array([[1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       ...,
       [1, 2, 3, 0, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5]])

In [32]:
np.argsort(raw_data_NAN_1, axis=0)

array([[ 166,  327,    0,   32,   32,  482],
       [ 847,  443,  673,  166,  166,  166],
       [ 846,  816,  674,   85,  448,   32],
       ...,
       [ 720,  812,  655, 1033,  718,  568],
       [ 568,  455,  624,  568, 1019,  978],
       [ 420,  733,  521,  718, 1033,   27]])

In [33]:
raw_data_NAN_1[np.argsort(raw_data_NAN_1[:,
                                        5])]

array([[ 1000.  ,    50.  ,   365.  ,  7468.93,  -350.  ,  -350.  ],
       [ 1000.  ,    50.  ,   365.  , -2550.  , -2100.  ,  1100.  ],
       [ 1000.  ,    50.  ,   365.  , -2870.  , -2870.  ,  1160.  ],
       ...,
       [ 9000.  ,   125.  ,   365.  , 16751.  , 16751.  , 54625.  ],
       [ 9000.  ,   125.  ,   365.  , 13001.  , 17001.  , 54625.  ],
       [ 9000.  ,   165.  ,   365.  ,  7468.93, 16846.  , 64001.  ]])

In [34]:
np.argsort(raw_data_NAN_1[:,5])

array([482, 166,  32, ..., 568, 978,  27])

In [35]:
raw_data_NAN_1[482]

array([1000.  ,   50.  ,  365.  , 7468.93, -350.  , -350.  ])

In [36]:
np.argwhere(raw_data_NAN_1 == False)

array([[116,   4],
       [430,   3]])

In [37]:
np.argwhere(np.isnan(raw_data_NAN_1))

array([], shape=(0, 2), dtype=int64)

In [38]:
np.isnan(raw_data_NAN_1).sum()

0

In [39]:
import numpy as np

File_Name_NAN = 'Lending-company-Numeric-NAN.csv'

raw_data_NAN_1 = np.genfromtxt(File_Name_NAN, 
           delimiter=';',
                             
           )
print(raw_data_NAN_1)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [   nan    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [40]:
np.isnan(raw_data_NAN_1).sum()

260

In [41]:
np.argwhere(np.isnan(raw_data_NAN_1))

array([[  11,    3],
       [  15,    3],
       [  27,    3],
       [  58,    3],
       [  60,    4],
       [  85,    4],
       [ 117,    5],
       [ 152,    1],
       [ 152,    2],
       [ 152,    4],
       [ 172,    1],
       [ 175,    1],
       [ 175,    2],
       [ 176,    3],
       [ 177,    4],
       [ 178,    5],
       [ 211,    3],
       [ 229,    0],
       [ 230,    1],
       [ 237,    1],
       [ 247,    3],
       [ 251,    5],
       [ 252,    4],
       [ 258,    1],
       [ 260,    3],
       [ 262,    4],
       [ 271,    5],
       [ 272,    4],
       [ 284,    2],
       [ 284,    3],
       [ 297,    1],
       [ 297,    2],
       [ 300,    3],
       [ 315,    3],
       [ 315,    5],
       [ 327,    4],
       [ 336,    4],
       [ 343,    0],
       [ 344,    2],
       [ 346,    2],
       [ 363,    3],
       [ 375,    3],
       [ 377,    2],
       [ 398,    5],
       [ 416,    4],
       [ 428,    0],
       [ 432,    1],
       [ 433,

In [42]:
raw_data_NAN_1[152]

array([ 9000.,    nan,    nan, 12251.,    nan, 34514.])

In [43]:
for index in np.argwhere(np.isnan(raw_data_NAN_1)):
    raw_data_NAN_1[index[0], index[1]] = 0

In [44]:
raw_data_NAN_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [    0.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [45]:
np.isnan(raw_data_NAN_1).sum()

0

In [46]:
from numpy.random import shuffle as sf
sf(raw_data_NAN_1)
raw_data_NAN_1

array([[ 1000.,    40.,   365.,  2540.,  3540., 15600.],
       [ 2000.,    40.,   365.,  3761.,  4161., 10761.],
       [ 4000.,    50.,   365.,     0.,  5240., 12910.],
       ...,
       [ 2000.,    50.,   365.,  4251.,  4951., 20250.],
       [ 2000.,    40.,   365.,  3401.,  4601., 16600.],
       [ 2000.,    50.,   365.,  3450.,     0., 20250.]])

In [47]:
(lambda x : x+1)(10)

11

In [48]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as psg

array_RG = gen(psg(seed = 365))
#array_RG.integers(low = 2, high = 15, size=(5,5))
array_RG.shuffle(raw_data_NAN_1)
raw_data_NAN_1

array([[ 2000.,    50.,   365.,  3500.,  5000., 20250.],
       [ 1000.,    40.,   365.,  2200.,  3760., 15600.],
       [ 2000.,    40.,   365.,  3401.,  4631., 12821.],
       ...,
       [ 1000.,    50.,   365.,   450.,  2050., 12000.],
       [ 2000.,    40.,   365.,  3581.,  4631., 16271.],
       [ 4000.,    50.,   365.,  5350.,  6500., 14400.]])

In [49]:
raw_data_NAN_1.astype(dtype = np.str).astype(dtype = np.float64).astype(dtype = np.int64)

/tmp/ipykernel_227/1697609751.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  raw_data_NAN_1.astype(dtype = np.str).astype(dtype = np.float64).astype(dtype = np.int64)


array([[ 2000,    50,   365,  3500,  5000, 20250],
       [ 1000,    40,   365,  2200,  3760, 15600],
       [ 2000,    40,   365,  3401,  4631, 12821],
       ...,
       [ 1000,    50,   365,   450,  2050, 12000],
       [ 2000,    40,   365,  3581,  4631, 16271],
       [ 4000,    50,   365,  5350,  6500, 14400]])

In [50]:
raw_data

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [51]:
raw_data_NAN_1

array([[ 2000.,    50.,   365.,  3500.,  5000., 20250.],
       [ 1000.,    40.,   365.,  2200.,  3760., 15600.],
       [ 2000.,    40.,   365.,  3401.,  4631., 12821.],
       ...,
       [ 1000.,    50.,   365.,   450.,  2050., 12000.],
       [ 2000.,    40.,   365.,  3581.,  4631., 16271.],
       [ 4000.,    50.,   365.,  5350.,  6500., 14400.]])

In [52]:
array_1 = np.array([['id_1','Product A'],['id_2', 'Product B'],['id_3', 'Product C']])
array_1[:,0] = np.chararray.strip(array_1[:,0], 'id_')
array_1[:,1] = np.chararray.strip(array_1[:,1], 'Product ')
array_1

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U9')

In [53]:
array_1[:,1] = np.where(array_1[:,1] == 'A',
                       1,
                       array_1[:,1])
array_1[:,1] = np.where(array_1[:,1] == 'B',
                       2,
                       array_1[:,1])
array_1[:,1] = np.where(array_1[:,1] == 'C',
                       3,
                       array_1[:,1])

In [54]:
array_1.astype(dtype = np.int64)

array([[1, 1],
       [2, 2],
       [3, 3]])

In [55]:
array_2 = np.array([[1,2,3,4,5],[3,4,5,6,7],[6,7,8,9,0],[2,5,7,9,1],[3,5,8,1,4]])
array_3 = array_2 *2

In [56]:
array_2

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [6, 7, 8, 9, 0],
       [2, 5, 7, 9, 1],
       [3, 5, 8, 1, 4]])

In [57]:
array_3

array([[ 2,  4,  6,  8, 10],
       [ 6,  8, 10, 12, 14],
       [12, 14, 16, 18,  0],
       [ 4, 10, 14, 18,  2],
       [ 6, 10, 16,  2,  8]])

In [58]:
np.stack((array_2, array_3), axis=1)

array([[[ 1,  2,  3,  4,  5],
        [ 2,  4,  6,  8, 10]],

       [[ 3,  4,  5,  6,  7],
        [ 6,  8, 10, 12, 14]],

       [[ 6,  7,  8,  9,  0],
        [12, 14, 16, 18,  0]],

       [[ 2,  5,  7,  9,  1],
        [ 4, 10, 14, 18,  2]],

       [[ 3,  5,  8,  1,  4],
        [ 6, 10, 16,  2,  8]]])

In [59]:
np.stack((array_2, array_3), axis=1).shape

(5, 2, 5)

In [60]:
np.dstack((array_2, array_3))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10],
        [ 6, 12],
        [ 7, 14]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16],
        [ 9, 18],
        [ 0,  0]],

       [[ 2,  4],
        [ 5, 10],
        [ 7, 14],
        [ 9, 18],
        [ 1,  2]],

       [[ 3,  6],
        [ 5, 10],
        [ 8, 16],
        [ 1,  2],
        [ 4,  8]]])

In [61]:
np.dstack((array_2, array_3))[:,0:2,0:2]

array([[[ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8]],

       [[ 6, 12],
        [ 7, 14]],

       [[ 2,  4],
        [ 5, 10]],

       [[ 3,  6],
        [ 5, 10]]])

In [62]:
np.dstack((array_2, array_3)).shape

(5, 5, 2)

In [63]:
np.concatenate((array_2, array_3), axis = 1)

array([[ 1,  2,  3,  4,  5,  2,  4,  6,  8, 10],
       [ 3,  4,  5,  6,  7,  6,  8, 10, 12, 14],
       [ 6,  7,  8,  9,  0, 12, 14, 16, 18,  0],
       [ 2,  5,  7,  9,  1,  4, 10, 14, 18,  2],
       [ 3,  5,  8,  1,  4,  6, 10, 16,  2,  8]])

In [66]:
np.unique(array_2, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 2, 3, 3, 4, 2, 3, 2, 2]))

In [67]:
array_2

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [6, 7, 8, 9, 0],
       [2, 5, 7, 9, 1],
       [3, 5, 8, 1, 4]])

In [68]:
array_2.shape

(5, 5)

In [70]:
array_check = np.array([[1,2,3],[4,5,6]])
array_check

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
np.reshape(array_check, (3,2))
#np.transpose(array_check)

array([[1, 2],
       [3, 4],
       [5, 6]])